[package]
name = "yeter"
version = "0.5.0"
edition = "2021"
description = "KISS incremental computation framework"
license = "GPL-3.0"

[dependencies]
anymap2 = "0.13.0"
thread_local = "1.1.7"
yeter-macros = { path = "macros", version = "0.4.0" }

[workspace]
members = ["macros"]
